import 'package:flutter/material.dart';
import 'package:network_http/model/post.dart';
import 'package:network_http/servic/emp.dart';
import 'package:network_http/servic/emp_list.dart';
import 'package:network_http/servic/employeOne.dart';
import 'package:network_http/servic/http.dart';
import 'package:network_http/servic/qoshimcha.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({
    Key? key,
  }) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  List<Employee> items = [];
  void _apiEplist() {
    Network.GET(Network.Api_Ep_list, Network.paramsNotempty())
        .then((response) => {print(response), _showresponse(response!)});
  }

  _showresponse(String response) {
    if (response != null) {
      Emplist emplist = Network.parshingEmplist(response);
      print(emplist.data!.first.employee_name);
      items = emplist.data!;
      setState(() {
        items = emplist.data!;
      });
    } else {
      print('Try again');
    }

    // EmpOne empOne = Network.parshingEmpone(response);
    // print(empOne.data!.employee_age);

    // Autogenerated autogenerated = Network.parshingQoshimcha(response);
    // print(autogenerated.data!.first.employeeName);
  }

  // String data = "";

  // void _apiGEt() {
  //   Network.GET(Network.Api_list, Network.paramsNotempty())
  //       .then((response) => {print(response), _showprint(response!)});
  // }

  // void _apiPost(Post post) {
  //   Network.POST(Network.Api_create, Network.paramsCreate(post))
  //       .then((response) => {print(response), _showprint(response!)});
  // }

  // void _apiPut(Post post) {
  //   Network.PUT(Network.Api_updata, Network.paramsUpdata(post))
  //       .then((response) => {print(response), _showprint(response!)});
  // }

  // void _apiDel(Post post) {
  //   Network.DEL(Network.Api_delete, Network.paramsNotempty())
  //       .then((response) => {print(response), _showprint(response!)});
  // }

  // void _showprint(String response) {
  //   setState(() {
  //     // data = response;
  //   });
  // }

  @override
  void initState() {
    super.initState();
    _apiEplist();
    // var post = Post(name: 'test', salary: '123', age: '23', id: '25');
    // _apiDel(post);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Employee List')),
      // body: Center(child: Text(data != null ? data : "No data")),
      body: ListView.builder(
        itemBuilder: ((context, index) {
          return itemOflist(items[index]);
        }),
        itemCount: items.length,
      ),
    );
  }

  Widget itemOflist(Employee emp) {
    return Container(
      padding: EdgeInsets.all(20),
      margin: EdgeInsets.only(bottom: 1),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            emp.employee_name! + emp.employee_age.toString(),
            style: const TextStyle(color: Colors.black, fontSize: 20),
          ),
          SizedBox(
            height: 20,
          ),
          Text('${emp.employee_salary}\$ ',
              style: const TextStyle(color: Colors.black, fontSize: 18))
        ],
      ),
    );
  }
}
